#!/bin/bash

if [ $# -eq 0 ]; then
	echo "No arguments supplied"
	exit 1
fi

if [ -z "$1" ]; then
	echo "No argument supplied"
	exit 1
fi

for i in `seq 1 4` ;
do
	echo "copy $1 to e$i"
	scp $1 e$i:$1
done
