#!/bin/bash

if [ $# -eq 0 ]; then
	echo "No arguments supplied"
	exit 1
fi

if [ -z "$1" ]; then
	echo "No argument supplied"
	exit 1
fi

echo "$1 @ em"
$1

for i in `seq 1 4` ;
do
	echo "$1 @ e$i"
	ssh e$i "$1"
done
